main: cn.wode490390.nukkit.sanctioner.Sanctioner
name: "Sanctioner"
description: "서버에 접속한 플레이어를 크래쉬 시킵니다."
authors: ["wode490390", "Wodor"]
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.6"]
load: POSTWORLD

permissions:
  sanctioner.crash:
    description: "/crash <플레이어>"
    default: op
  sanctioner.stuck:
    description: "Allows a player to use /stuck"
    default: op
